### PR TITLE
Fixes #38: Update layout and styling of register page

### LINKED ISSUE #38: Improve styling and UI of Register as alumni page
image
The register as alumni page appears to be a basic form as of now. 

Proposed improvements - 
use a gradient as a background colour
restructure the form inputs - instead of stacking the input fields as a single column, use a table-like layout and add a image / design in the remaining screen space.
change hover effect of submit button.

@abhishekraoas please assign it to me with gssoc-extend and hacktoberfest labels.

### PR DESCRIPTION
**Pull request by jainaryan04**
please add gssoc and hacktoberfest labels @abhishekraoas 

image

### CODE REVIEW

**Comment by abhishekraoas** [comment]
make it in 2 columns only and use some svg icon in side

**Comment by jainaryan04** [comment]
updated as asked

image

**Comment by abhishekraoas** [comment]
Firstly make sure your branch is up to date with the main and there should not be any code conflict

**Comment by jainaryan04** [comment]
where do you want me to add the login button, next to the register button ?
but is not there is a separate login page for that ?
image
image

**Comment by abhishekraoas** [comment]
In the Register form, you added a register button there and I want add Login Button also and link to the login page

**Comment by jainaryan04** [comment]
done @abhishekraoas 

image

**Comment by jainaryan04** [comment]
could not fix the App.jsx issue but I have styled the Register page and added the Login button to navigate to Login page.
@abhishekraoas

**Comment by abhishekraoas** [comment]
raise a PR in Contribution branch for avoid code conflict

**Pull request closed without merging**
