### PR TITLE
#Ads  Code_Of_Conduct.md

### LINKED ISSUE #4: Add Code of Conduct
I would like to add a code of conduct developed for your repository. Please let me know if it is okay to proceed. Please assign to me and add GSSoC24 Ext Labels.

### PR DESCRIPTION
**Pull request by KiranBaliga**
closes #4 

This PR addresses the addition of code of conduct markdown file to your repo. The file has been modified to meet the usage guidelines of the MCA alumni network and email ID of the author has been added for reporting purposes. Thank you. Please review and action accordingly.

### CODE REVIEW

**Comment by KiranBaliga** [comment]
@abhishekraoas can you please add level1 and GSSoC-Ext labels please. Thank you!

**Comment by aditya-bhaumik** [comment]
@abhishekraoas why have you not given the gssoc-ext label ??

Also you can give level 1 for document updates

**Comment by aditya-bhaumik** [comment]
@abhishekraoas please add the labels

**Comment by MastanSayyad** [comment]
@KiranBaliga added

**Pull request merged**
