### PR TITLE
fixed the broken image in register section

### PR DESCRIPTION
**Pull request by Sameeratweb**
Screenshot 2024-10-13 084542
I've fixed the broken image with original source image. I hope to  merge it with the relevant tags.

### CODE REVIEW

**Comment by abhishekraoas** [comment]
> Screenshot 2024-10-13 084542 I've fixed the broken image with original source image. I hope to merge it with the relevant tags.

update your branch with the main branch

**Comment by Sameeratweb** [comment]
is it possible to merge with this branch itself

**Comment by abhishekraoas** [comment]
> is it possible to merge with this branch itself

no you have to update your branch with main branch of this project

**Comment by abhishekraoas** [comment]
your branch is updated now I'm merging this PR.

**Review by abhishekraoas — APPROVED** [review]

**Pull request merged**
