### PR TITLE
Add new feature:Enhanced UI by adding proper margins and implementing…

### PR DESCRIPTION
**Pull request by DevanshS9881**
### Enhancements for the Alumni Page:

1. I have implemented appropriate margins for the main container, creating sufficient spacing from the navigation bar, which enhances the clarity of the website.

2. I have introduced a hover effect for the GitHub profile SVG, mirroring the effect previously applied to the LinkedIn SVG. Additionally, to enhance interactivity, a similar hover effect has been applied to the UserCards.

image

### CODE REVIEW

**Comment by abhishekraoas** [comment]
There is nothing happened 
{2E246C5C-2604-41E0-B4B1-B3FD93B93BAD}

**Comment by DevanshS9881** [comment]
I am very sorry for the inconvenience. I think this issue was because I did not update the main branch of my forked repo with the changes (as I did it for the new branch which I created) and also because I missed adding a modified file to the staging area . So now I have updated the main branch , recommitted my work and I hope it works fine and in case , it doesn't then I am open to any recommendation or suggestions by you.

**Comment by abhishekraoas** [comment]
> I am very sorry for the inconvenience. I think this issue was because I did not update the main branch of my forked repo with the changes (as I did it for the new branch which I created) and also because I missed adding a modified file to the staging area . So now I have updated the main branch , recommitted my work and I hope it works fine and in case , it doesn't then I am open to any recommendation or suggestions by you.

again update your branch

**Comment by DevanshS9881** [comment]
Sure , I have updated my branch . Please review

**Review by abhishekraoas — APPROVED** [review]

**Pull request merged**
