### PR TITLE
font family and x logo replaced

### PR DESCRIPTION
**Pull request by Navneetdadhich**
1. replaced the logo of X, on the place of old twitter logo .
2. changed the font family to poppins from roboto. Its looking more classic than before.
3. on the ui part i have seen website after 3 days and it completely changed so i didnt applied anything on ui part.
4. i have created a hover effect on logo so its looks more attentive by hovering on logo.
#18 

**before**

TWITTER

**After**

xlogo

please merge this PR under gssoc and hacktoberfest.
Thank you owner @abhishekraoas for giving me this opportunity.

### CODE REVIEW

**Comment by abhishekraoas** [comment]
There is a code conflict and update your branch with the main branch.

{A713A1A8-F989-48AD-91E2-FD97FC3644E7}

**Comment by Navneetdadhich** [comment]
i have change the content of footer

**Comment by abhishekraoas** [comment]
> i have changed the content of footer

update your branch with the main

**Comment by Navneetdadhich** [comment]
done

**Comment by Navneetdadhich** [comment]
hello @abhishekraoas how can i solve these conflicts please give some reference.

**Comment by Navneetdadhich** [comment]
hello sir @abhishekraoas  i have resolved the issue of the branch conflict now you can merge it.

**Pull request closed without merging**
