### PR TITLE
[UI Enhancement] : added Gsap animation to navbar and home page fixes #134

### LINKED ISSUE #134: [UI ENHANCEMENT] : Adding GSAP animation to Home page | gssoc-ext | level 3
### **Adding GSAP animation to Home page | gssoc-ext | level 3**

Please assign this to me under gssoc-ext level 3

### PR DESCRIPTION
**Pull request by Hamza1821**
### **please assign this to me under gssoc-ext level 3**

fixes #134 

demo

https://github.com/user-attachments/assets/6ca0f2c3-3a1e-4cfe-9704-9d9d7abe6744

### CODE REVIEW

**Comment by abhishekraoas** [comment]
After navigating to the other page and after back to the homepage then the homepage text is not visible.

{73C67FD3-BB9F-49ED-AC04-AE414ADE3010}

**Comment by Hamza1821** [comment]
ok  i am looking into it

**Comment by Hamza1821** [comment]
sir i have fixed the issue now kindly please assign this to me under gssoc-ext level 3 and please merge it,

**Review by abhishekraoas — APPROVED** [review]

**Comment by Hamza1821** [comment]
sir please add level 3

**Comment by Hamza1821** [comment]
@abhishekraoas you have not assigned me this pr which is affecting my score in gssoc-ext also kindly label this levl 3 as it took me hours to just integrate gsap to your project

**Comment by Hamza1821** [comment]
> @abhishekraoas you have not assigned me this pr which is affecting my score in gssoc-ext also kindly label this levl 3 as it took me hours to just integrate gsap to your project

**Comment by abhishekraoas** [comment]
@Hamza1821 I have already done it. It will take time to update.

**Pull request merged**
