### PR TITLE
improved UI's of about page

### PR DESCRIPTION
**Pull request by SHRIVISHNU-CM**
@abhishekraoas I just made responsive about page. In this page, I added a register link it directly take register page.
#106 issue fixed 
Before Image:
Screenshot 2024-10-07 105603
After Image:
Screenshot 2024-10-07 105816
@abhishekraoas Please merge this PR.

### CODE REVIEW

**Comment by abhishekraoas** [comment]
Its looking not good improve it and make it professional

**Comment by SHRIVISHNU-CM** [comment]
@abhishekraoas  give me some time I will improve it

**Comment by SHRIVISHNU-CM** [comment]
@abhishekraoas I just improved the about page with framer motion. Please check
fixed issue #116

**Comment by SHRIVISHNU-CM** [comment]
@abhishekraoas  included social media links and other sections with interactive motion on scrolling.

**Comment by SHRIVISHNU-CM** [comment]
https://github.com/user-attachments/assets/50d228aa-8dd9-4ca4-ab13-a2fc26553210

@abhishekraoas 
check this

**Comment by abhishekraoas** [comment]
There is code conflict and design like this GSSoC About Page
image

**Comment by SHRIVISHNU-CM** [comment]
@abhishekraoas give some time I will resolve it

**Comment by SHRIVISHNU-CM** [comment]
@abhishekraoas As per your suggestion, I improved the page. It is also responsive for large and mobile screens. I maintained the background of the home page and the color of the social media icons.
issue #106 
Screenshot 2024-10-09 192319
Screenshot 2024-10-09 192405

**Comment by abhishekraoas** [comment]
Looking good do one thing first change background color use the black color for background and there is a code conflict so first resolve it

{037C7E45-0567-4184-ABBF-87C7271498C8}

**Comment by SHRIVISHNU-CM** [comment]
@abhishekraoas ok give me some time I finish it

**Pull request closed without merging**
