### PR TITLE
Fix: Resolve login failure issue due to password comparison

### LINKED ISSUE #315: BUG: FIx the Login Failure issue
Here's a sample GitHub issue template for the login failure:

---

#### Issue Description
Users are unable to log in due to a password comparison failure in the `handleUserLogin` controller. Despite entering the correct credentials, login attempts are rejected with an "Invalid credentials" error.

#### Steps to Reproduce
1. Sign up a new user account with a password.
2. Attempt to log in using the correct email and password.

#### Expected Behavior
The login should succeed if the correct email and password are provided.

#### Actual Behavior
The login fails, returning an "Invalid credentials" error, even when the correct password is entered.

#### Possible Causes
- Manual re-hashing of the password before comparison may be causing the mismatch.
- There might be an issue with how bcrypt compares the plaintext password with the hashed password.

#### Suggested Solution
- Ensure `bcrypt.compare` is used directly for comparing the plaintext password from the request with the hashed password stored in the database.
- Double-check that the password is properly hashed and saved during the signup process.

#### Code Snippet (if applicable)

```javascript
// Handle Login
const isMatch = await bcrypt.compare(password, userExist.password);
if (isMatch) {
  // proceed with login
} else {
  // handle failed login
}
```

---

---

This issue template should provide the development team with all the context needed to address the login failure problem effectively.

### PR DESCRIPTION
**Pull request by veepanshu-kasana**
## Description

This pull request addresses the issue where users were unable to log in due to a password comparison failure in the `handleUserLogin` controller.

The issue was caused by the way the server was returning the data, which was not being handled correctly on the client-side. The updated `handleLogin` function now includes an additional check to ensure the plaintext password from the form matches the hashed password stored in the database using `bcrypt.compare`. This resolves the "Invalid credentials" error that users were experiencing during login.

## Changes

1. Updated the `handleLogin` function to use `bcrypt.compare` to directly compare the plaintext password from the form with the hashed password stored in the database.
2. Improved error handling to display a more specific "Invalid credentials" error message to the user if the password comparison fails.
3. Added additional logging and error handling to the `catch` block to help with debugging any future issues.

## Fixes

Resolves #315 - Login failure due to password comparison issue

### CODE REVIEW

**Comment by veepanshu-kasana** [comment]
@abhishekraoas Why my pull request got failed bro!

**Comment by abhishekraoas** [comment]
> ## Description
> This pull request addresses the issue where users were unable to log in due to a password comparison failure in the `handleUserLogin` controller.
> 
> The issue was caused by the way the server was returning the data, which was not being handled correctly on the client-side. The updated `handleLogin` function now includes an additional check to ensure the plaintext password from the form matches the hashed password stored in the database using `bcrypt.compare`. This resolves the "Invalid credentials" error that users were experiencing during login.
> 
> ## Changes
> 1. Updated the `handleLogin` function to use `bcrypt.compare` to directly compare the plaintext password from the form with the hashed password stored in the database.
> 2. Improved error handling to display a more specific "Invalid credentials" error message to the user if the password comparison fails.
> 3. Added additional logging and error handling to the `catch` block to help with debugging any future issues.
> 
> ## Fixes
> Resolves #315 - Login failure due to password comparison issue

Still not working. can you share the video of login steps

**Comment by veepanshu-kasana** [comment]
@abhishekraoas Despite my attempts to resolve the issue, I have not been able to fully fix the problem yet. I apologize for not being able to resolve this, Thank you for your understanding.

**Comment by veepanshu-kasana** [comment]
> > @abhishekraoas Despite my attempts to resolve the issue, I have not been able to fully fix the problem yet. I apologize for not being able to resolve this, Thank you for your understanding.
> 
> Can you fix it or not ?

I can't apologise for it!

**Pull request closed without merging**
