### PR TITLE
I have fixed your side social media icons :)

### PR DESCRIPTION
**Pull request by Vatsal-Verma**
i have fixed the bug of the side social links , You can check it :)

### CODE REVIEW

**Comment by Vatsal-Verma** [comment]
issue number : #141

**Comment by abhishekraoas** [comment]
@Vatsal-Verma first update you branch with the main branch of the project

**Comment by Vatsal-Verma** [comment]
Hey @abhishekraoas the branch is already updated wrt the main branch, PTAL : )

**Comment by abhishekraoas** [comment]
> Hey @abhishekraoas the branch is already updated wrt the main branch, PTAL : )

Your branch is not updated with the main branch

**Comment by Vatsal-Verma** [comment]
image

it says updated.

**Comment by abhishekraoas** [comment]
Updated branch
image


your branch
image

**Comment by abhishekraoas** [comment]
Already merge

**Pull request closed without merging**
