### PR TITLE
Dockerfile Updated Fixes #58

### LINKED ISSUE #58: Creating Dockerfile To Instantly Spin Up Backend Services Without Any Config
Hey  @abhishekraoas 

I can see that there is no Dockerfile in your project for backend . I can create a one for you so that contributors can straight run it and start working.

Please assign me this issue under gssoc ext level3

### PR DESCRIPTION
**Pull request by rishyym0927**
image

Hey As you can see the docker file is running successfully , now user can run the docker file smoothly without any issue and fixes #58

### CODE REVIEW

**Comment by abhishekraoas** [comment]
Firstly make sure your branch is up to date with the main and there should not be any code conflict

**Comment by rishyym0927** [comment]
there is no branch conflict, please merge it

**Comment by rishyym0927** [comment]
Hey @abhishekraoas  There is no merge conflict in this pr, please merge it

**Comment by rishyym0927** [comment]
@anki2003ta  Please add label gssoc-ext Level3 . Else it wont be counted. 
Please check the spelling and correct it

**Pull request merged**
