### PR TITLE
UI Enhanced of ContactUs Page

### LINKED ISSUE #202: Enhacing ContactUs Section's UI
image

This UI can be improved to make it look more attractive and better by using a combination of colors, adjusting properties, and ensuring correct alignment.

Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.

### PR DESCRIPTION
**Pull request by Bhum-ika**
I have made the required modifications 

image

Fixed #202 

If you like it, kindly upgrade my level, I would really appreciate

### CODE REVIEW

**Comment by abhishekraoas** [comment]
We don't need the other style of contact us. It's already matched with our form.

**Comment by Bhum-ika** [comment]
@abhishekraoas The background color is matching with other pages of your website, if you want i can remove this gradient color

**Comment by abhishekraoas** [comment]
> @abhishekraoas The background color is matching with other pages of your website, if you want i can remove this gradient color

but it's already done. you can work on the other components

**Comment by Bhum-ika** [comment]
You assigned me the issue. And now you are denying. I invested my time on it

**Comment by abhishekraoas** [comment]
> You assigned me the issue. And now you are denying. I invested my time on it. You should have told me before.

@Bhum-ika Sorry for that, But I didn't assigned you. I think my team done this. The Contact us form design was already done. but you had wanted redesign the Contact us form, don't worry remove the gradient color after that i will review and merge your PR

**Comment by Bhum-ika** [comment]
okay

**Comment by Bhum-ika** [comment]
Please check

**Comment by abhishekraoas** [comment]
> Please check

Your branch is not update with the main branch of the project. update it.

**Comment by Bhum-ika** [comment]
Its updated from my side

**Review by abhishekraoas — APPROVED** [review]

**Pull request merged**
