### PR TITLE
Updated about section

### PR DESCRIPTION
**Pull request by SHRIVISHNU-CM**
@abhishekraoas Please check I resolved conflict 
Screenshot 2024-10-09 214444
#106 fixed

### CODE REVIEW

**Comment by abhishekraoas** [comment]
Looking good but need some improvement.
1. Change the SVG Image.
2. Use the small font size for the Paragraph.
3. Change the Design of Button make like Login and Register Button.

**Comment by SHRIVISHNU-CM** [comment]
@abhishekraoas ok i will do

**Comment by SHRIVISHNU-CM** [comment]
@abhishekraoas check once changed as you told 

1. Changed SVG image
2. Minimized P font
3. changed the login button
4. also made responsive. there was issue with mobile screen, but now its perfect

**Comment by abhishekraoas** [comment]
No you changed only svg and its looking not good and button width is not proper

**Comment by SHRIVISHNU-CM** [comment]
@abhishekraoas please check I changed as you said.

**Comment by SHRIVISHNU-CM** [comment]
@abhishekraoas This task was assigned to me, right?

**Comment by SHRIVISHNU-CM** [comment]
@abhishekraoas do I need to close this pull request? Because you already merged other about page code

**Pull request closed without merging**
