### PR TITLE
Revamped Alumni Search and User Card Design

### PR DESCRIPTION
**Pull request by IkkiOcean**
## Description
This PR introduces two major enhancements to the alumni section:

1. **Search Component**
   - Implemented a search component that allows filtering by **Name**, **Skills**, **Batch**, and **City**. This provides users with a more refined search experience.

2. **User Card Design**
   - Revamped the alumni card with a modern aesthetic, improving the overall look and feel of the alumni profiles.

## Changes Made:
- **Search Component**
  - Added filter options for **Name**, **Skills**, **Batch**, and **City** to enhance user search capabilities.

- **User Card**
  - Updated the layout and styling of the alumni card to align with contemporary design trends, ensuring a visually appealing presentation of alumni information.

## How to Test
1. Pull the latest changes to your local branch.
2. Start the development server and navigate to the `Our Alumni` section.
3. Test the search functionality by filtering alumni based on different criteria.
4. Review the updated user card design to ensure it meets the aesthetic standards.

## Related Issues
- Closes : #194 

## Video

https://github.com/user-attachments/assets/b39514b0-1e48-4a89-a6ff-48af5921471e

### CODE REVIEW

**Comment by IkkiOcean** [comment]
**Please provide level-3**, since I created and implemented multiple components for this page. The feature I added were added in a scalable manner and are really useful for users. so please consider

**Comment by abhishekraoas** [comment]
> **Please provide level-3**, since I created and implemented multiple components for this page. The feature I added were added in a scalable manner and are really useful for users. so please consider

Looking Good, But need some improvement 
1. First update your branch with the main branch.
2. Change the UI of Search bar design like Login and Register theme UI.
3. User card is too big, make it small.

**Comment by IkkiOcean** [comment]
@abhishekraoas done! 

https://github.com/user-attachments/assets/624d0d3b-0323-4169-83fb-5eb5c72a16d6

**Review by abhishekraoas — APPROVED** [review]

**Comment by IkkiOcean** [comment]
@abhishekraoas please add level and gddoc tags

**Comment by IkkiOcean** [comment]
@abhishekraoas sir, we get level 1 for documents update? atleast make it 2

**Comment by abhishekraoas** [comment]
> @abhishekraoas sir, we get level 1 for documents update? atleast make it 2

done

**Pull request merged**
