### PR TITLE
Implement PR Issue Checker Workflow

### PR DESCRIPTION
**Pull request by smog-root**
**FIX** #232 

**Usage:**

1. When a pull request is created or edited, the workflow automatically triggers.

2. The workflow checks for:
- A non-empty PR description.
- A valid issue reference format (`FIX #<issue-number>` or `FEAT, or DOC #NEW`).
3. If either check fails, the PR will be marked as failing, and the author will receive clear error messages in the PR comments.
4. If all checks pass, a confirmation message will indicate that the PR is valid.

**_Note_**: Kindly add all the labels added to the issue, to this PR!

@abhishekraoas

### CODE REVIEW

**Comment by abhishekraoas** [comment]
First update your branch with the main

**Comment by smog-root** [comment]
> First update your branch with the main

It's up to date! you can merge it this was! it's more secure! @abhishekraoas

**Comment by abhishekraoas** [comment]
> > First update your branch with the main
> 
> It's up to date! you can merge it this was! it's more secure! @abhishekraoas

your branch has not been updated yet. update it

**Comment by smog-root** [comment]
> > > First update your branch with the main
> > 
> > 
> > It's up to date! you can merge it this was! it's more secure! @abhishekraoas
> 
> your branch has not been updated yet. update it

Screenshot (30)

It's updated! 

merge it!

**Review by abhishekraoas — APPROVED** [review]

**Comment by smog-root** [comment]
Dude. In the issue you added level3. But in the PR you added level1.

Please make it atleast level2!! @abhishekraoas

**Pull request merged**
