### PR TITLE
Re-Design About Us page with modern ui features

### PR DESCRIPTION
**Pull request by mdfaizaanalam**
1. Befor About-Us page layout.

About

2. After Modification and redesigning About-US page.

https://github.com/user-attachments/assets/0328a612-8b6b-4ee0-a669-1e6651c01832

I have re- design About Us page by using Material UI to deliver a clean, responsive layout with enhanced user experience. Framer Motion was integrated to add dynamic hover effects and smooth animations, creating an interactive and engaging design. A fixed header ensures seamless navigation, allowing users to easily explore different sections of the page. This combination of technologies results in a polished and intuitive About Us page, improving both aesthetics and usability.

### CODE REVIEW

**Comment by mdfaizaanalam** [comment]
@abhishekraoas Hey I have fix the issue #31 which you have assaign to me.
Re-design #103  About us page as per suggestion.

I have improved the About Us page by using modern ui, motion framer, material UI features in it.

**Comment by abhishekraoas** [comment]
Remove the our team section

**Comment by abhishekraoas** [comment]
design like this simple. don't use animation in font
{3C081733-6496-4ABF-A4CE-5CBD0AB456D3}

**Comment by mdfaizaanalam** [comment]
@abhishekraoas as you have suggest i have removed the animation from font, now you can check.

**Comment by abhishekraoas** [comment]
{F34BE804-7E9D-460C-AED4-616DEA4CDE31}
the register form image is missing make sure everything is alright and redesign like GSSoC About Page

**Comment by mdfaizaanalam** [comment]
@abhishekraoas  I have not change anything in the register page check it again this changes is not done by me.

**Comment by mdfaizaanalam** [comment]
@abhishekraoas Please check it again i have not done any changes in the register page.

Screenshot 2024-10-09 092931



Ab

And also about us page is look similar to gssoc about us page.

**Comment by mdfaizaanalam** [comment]
@abhishekraoas  Please add label in it.

And also please add label in #99  which you have already merged.

**Comment by mdfaizaanalam** [comment]
@abhishekraoas Now please check it and merge it.
Also please add label in it.

**Comment by mdfaizaanalam** [comment]
@abhishekraoas And i request you to please add atleast level 2 beacuse i have made complete home page and about us page for your website.

**Comment by mdfaizaanalam** [comment]
@abhishekraoas i have fix the conflict issue now you can check and merge it.

**Comment by mdfaizaanalam** [comment]
@abhishekraoas please check it i have fix the issue.

**Comment by abhishekraoas** [comment]
> @abhishekraoas please check it i have fix the issue.

Looking Good, do one thing change the background color and use the black color

**Comment by abhishekraoas** [comment]
> Screenshot 2024-10-10 193835
> 
> @abhishekraoas As you suggest change the background to black. Now, please check.

Can you change background color of the home page also.

**Comment by mdfaizaanalam** [comment]
@abhishekraoas which colour you want for home page?

**Comment by mdfaizaanalam** [comment]
@abhishekraoas Now, please check i have change the background colour for home page also.

**Comment by abhishekraoas** [comment]
> @abhishekraoas Now, please check i have change the background colour for home page also.

Good, but your branch is not updated please update your branch with the main branch

**Pull request closed without merging**
