### PR TITLE
added gsap animations to landing page | gssoc-ext | level 3 fixes #134

### LINKED ISSUE #134: [UI ENHANCEMENT] : Adding GSAP animation to Home page | gssoc-ext | level 3
### **Adding GSAP animation to Home page | gssoc-ext | level 3**

Please assign this to me under gssoc-ext level 3

### PR DESCRIPTION
**Pull request by Hamza1821**
### *i have first integrate GSAP to react then created UseEffect for rendering animation when page is loaded , inside useEffect i have created a gsap context that make sure that animations are played only when the component is already rendered than i have use gsap fromTo mehode use create the desire animations, also i will be using GSAP timeline for even better and time sync animations*

fixes : #134 

### **_please asign this to me under  gssoc-ext level 3_**

Demo 

https://github.com/user-attachments/assets/4fcb6c2d-85bb-416d-93a6-5f130d500b1d

### CODE REVIEW

**Comment by abhishekraoas** [comment]
After doing all these things. it's not looking good fix it ASAP.
{5E978B36-C349-4170-B6CA-58F40BAD2387}

**Comment by Hamza1821** [comment]
If you are talking about "register as alumni"  and login button then i have not touch it .it was like that beforehand

**Comment by Hamza1821** [comment]
I just have added sliding animation to navbar and home page

**Comment by Hamza1821** [comment]
if you have no issues with the gsap animations that i have added then i request you to merge this PR under gssoc-ext and level 3

**Comment by abhishekraoas** [comment]
check the main branch of the project.
{A306FD3E-9B5F-4A6F-98D1-A25294F16269}

**Comment by Hamza1821** [comment]
ok i will look into this

**Pull request closed without merging**
