### PR TITLE
#145 Improve Form Handling and UI Enhancements for Sign Up Page

### PR DESCRIPTION
**Pull request by agrawal-2005**
#145 This pull request includes the following improvements:

1. **Form Handling for Sign In and Sign Up:**
   - Enhanced input validation (e.g., email format and password length).
   - Improved error state management for clearer user feedback.
   - Ensured smoother form submission and error handling.

2. **UI Improvements for Sign Up Page:**
   - Redesigned UI for a more visually appealing and user-friendly experience.
   - Improved spacing, font adjustments, and overall responsiveness.
   - Enhanced button styles and error displays for a cleaner appearance.

### CODE REVIEW

**Comment by abhishekraoas** [comment]
The old design is looking good. if you want to add something in the Register form then you can fix input alignment and both can align in the center.

{AADE530D-75AF-4D64-85C3-2D4405A633EA}

**Comment by agrawal-2005** [comment]
Screenshot 2024-10-14 at 12:15:54 AM
@abhishekraoas, see I have resolved the issue as you told me.

**Comment by abhishekraoas** [comment]
There are code conflicts first resolve it.
{0BCA0F13-1401-41E8-84B5-F6E03C530F27}

**Comment by agrawal-2005** [comment]
@abhishekraoas, there is no conflict.

**Pull request merged**
