### PR TITLE
Update Landing page design for Better User Engagement

### PR DESCRIPTION
**Pull request by mdfaizaanalam**
https://github.com/user-attachments/assets/91affdeb-4ab7-4850-850d-c313b00b8130

I have design landing page using a multi-column grid with Material UI for better layout and organization, and added engaging hover effects and animations with Framer Motion for an interactive user experience. The fixed header improves navigation by making it easy to access different sections.

### CODE REVIEW

**Comment by mdfaizaanalam** [comment]
@abhishekraoas Hey I have fix the issue #35 which you have assaign to me, and update pull request #78

I have improved the home page by using modern ui, motion framer, material ui features in it.

**Review by abhishekraoas — APPROVED** [review]

**Comment by abhishekraoas** [comment]
Hii @mdfaizaanalam please raise a new PR of this issue. The main branch has been conflict I want merge this PR again to the main

**Comment by mdfaizaanalam** [comment]
@abhishekraoas  Please add labels in this
hacktoberfest-accepted
gssoc-ext

**Comment by mdfaizaanalam** [comment]
@abhishekraoas Please add label in it
gssoc-ext
hacktoverfest-accepted

Because of this my contribution is not showing in leaderboard.

**Pull request merged**
